Include benchmarking entrypoint out of the box.
Benchmarking will *always* get complicated because you almost certainly care very much about details like running enough to learn but not too much to get slow, feeding that info to other postprocessors, etc.  But you should really at least *know how* to get started in one word.  (And unfortunately, there's some serious apocrypha around go benchmarking, like the "XXX" bit here.)

diff --git a/goad b/goad
--- a/goad
+++ b/goad
@@ -77,6 +77,22 @@ else
 	install)
 		go install -ldflags "$LDFLAGS" "$cmd"
 		;;
+	bench)
+		profPath="$GOPATH/tmp/prof/"
+		mkdir -p "$profPath"
+		set +e ; shift ; shift ; set -e
+		go test -i "$SUBSECTION" "$@" &&
+		GOCONVEY_REPORTER=silent \
+		go test \
+			-run=XXX -bench=. \
+			-o "$profPath/bench.bin" \
+			-cpuprofile="$profPath/cpu.pprof" \
+			"$SUBSECTION" "$@"  || {
+				echo -e "\E[1;41msome benchmarks failed!\E[0;m"
+				exit 4
+		}
+		# use e.g.: go tool pprof --text .gopath/tmp/prof/bench.bin .gopath/tmp/prof/cpu.pprof
+		;;
 	fmt)
 		go fmt "$SUBSECTION"
 		;;
@@ -108,7 +124,7 @@ else
 		rm -rf "$GOPATH/bin" "$GOPATH/pkg" "$GOPATH/tmp"
 		;;
 	*)
-		echo "Usage: $0 {init|test|install|fmt|doc|cover|clean}" 1>&2;
+		echo "Usage: $0 {init|test|install|bench|fmt|doc|cover|clean}" 1>&2;
 		exit 1
 	;;
 	esac
